---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: amazonwebappdeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: amazonwebapp
 template:
  metadata:
   name: amazonwebapppod
   labels:
     app: amazonwebapp	 
  spec: 
    containers:
    - name: amazonwebappcontainer
      image: krishna0369/amazonwebapp
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: amazonwebappsvc
spec:
  type: LoadBalancer
  selector:
   app: amazonwebapp
  ports:
   - port: 80
     targetPort: 8080
...
